exp_result:
  local-ssd:
    fn: local-ssd-160307-024338-160302-151235
    #fn: local-ssd-160302-151235
    short-name: LS
  ebs-ssd:
    fn: ebs-ssd-160302-212229
    short-name: ES
  ebs-mag:
    fn: ebs-mag-160302-193548
    short-name: EM
  local-ssd-ebs-mag:
    fn: local-ssd-ebs-mag-160307-011346-160303-004309
    #fn: local-ssd-ebs-mag-160307-011346
    #fn: local-ssd-ebs-mag-160303-004309
    short-name: LSEM
  local-ssd-ebs-ssd:
    fn: local-ssd-ebs-ssd-160302-230443
    short-name: LSES
  local-ssd-local-ssd:
    fn: local-ssd-local-ssd-160306-013355
    short-name: LSLS
